export const SEED_JOBS = [
  {
    title: 'Senior QA Automation Engineer',
    company: 'Stripe',
    location: 'Remote',
    remote: true,
    salary: '$140K - $180K',
    salary_min_usd: 140000, salary_max_usd: 180000, salary_currency: 'USD',
    skills: ['Playwright', 'TypeScript', 'CI/CD', 'API Testing', 'SQL', 'Postman'],
    description: 'Build and maintain end-to-end automation for payment flows using Playwright and TypeScript. Own CI pipelines, write API tests, and partner with engineering to raise the release quality bar.',
    hiring_speed: 'Fast', company_logo: 'ST', posted: '2 days ago', type: 'Full-time',
    apply_url: 'https://stripe.com/jobs', source: 'seed', country: null, category: 'QA',
  },
  {
    title: 'Manual Software Tester',
    company: 'Infosys',
    location: 'Bengaluru, India',
    remote: false,
    salary: '\u20b94L - \u20b98L',
    salary_min_usd: 5000, salary_max_usd: 10000, salary_currency: 'INR',
    skills: ['Manual Testing', 'JIRA', 'Test Cases', 'Agile', 'Bug Reporting', 'Regression'],
    description: 'Perform functional and regression testing across web and mobile applications. Author test cases in JIRA, execute test plans, and report defects with clear repro steps.',
    hiring_speed: 'Moderate', company_logo: 'IN', posted: '1 day ago', type: 'Full-time',
    apply_url: 'https://www.infosys.com/careers/', source: 'seed', country: 'IN', category: 'QA',
  },
  {
    title: 'Full Stack Software Engineer',
    company: 'Vercel',
    location: 'Remote (US)',
    remote: true,
    salary: '$160K - $220K',
    salary_min_usd: 160000, salary_max_usd: 220000, salary_currency: 'USD',
    skills: ['Next.js', 'React', 'TypeScript', 'Node.js', 'PostgreSQL', 'AWS'],
    description: 'Build the future of the web at Vercel. Ship product features across our Next.js, edge runtime and dashboard stack.',
    hiring_speed: 'Fast', company_logo: 'VC', posted: '5 hours ago', type: 'Full-time',
    apply_url: 'https://vercel.com/careers', source: 'seed', country: 'US', category: 'Software',
  },
  {
    title: 'SDET - QA Engineer',
    company: 'Zoho',
    location: 'Chennai, India',
    remote: false,
    salary: '\u20b98L - \u20b914L',
    salary_min_usd: 10000, salary_max_usd: 17000, salary_currency: 'INR',
    skills: ['Selenium', 'Java', 'TestNG', 'SQL', 'API Testing', 'Postman'],
    description: 'Design, develop and maintain automated test frameworks using Selenium + Java. Write robust API tests and collaborate with dev teams on quality strategy.',
    hiring_speed: 'Fast', company_logo: 'ZH', posted: '3 days ago', type: 'Full-time',
    apply_url: 'https://www.zoho.com/careers/', source: 'seed', country: 'IN', category: 'QA',
  },
  {
    title: 'Frontend Engineer (React)',
    company: 'Linear',
    location: 'Remote',
    remote: true,
    salary: '$150K - $200K',
    salary_min_usd: 150000, salary_max_usd: 200000, salary_currency: 'USD',
    skills: ['React', 'TypeScript', 'CSS', 'Zustand', 'Design Systems', 'Framer Motion'],
    description: 'Craft high-performance interfaces with obsessive attention to detail. You will own major surface areas of the Linear app.',
    hiring_speed: 'Moderate', company_logo: 'LI', posted: '1 week ago', type: 'Full-time',
    apply_url: 'https://linear.app/careers', source: 'seed', country: null, category: 'Software',
  },
  {
    title: 'Data Engineer',
    company: 'Razorpay',
    location: 'Bengaluru, India',
    remote: false,
    salary: '\u20b918L - \u20b932L',
    salary_min_usd: 22000, salary_max_usd: 40000, salary_currency: 'INR',
    skills: ['Python', 'SQL', 'Airflow', 'Spark', 'AWS', 'ETL'],
    description: 'Build data pipelines that power analytics and ML at Razorpay. Design robust ETL/ELT workflows on Airflow and Spark.',
    hiring_speed: 'Moderate', company_logo: 'RZ', posted: '4 days ago', type: 'Full-time',
    apply_url: 'https://razorpay.com/jobs/', source: 'seed', country: 'IN', category: 'Data',
  },
  {
    title: 'Junior Software Engineer (Fresher)',
    company: 'TCS',
    location: 'Pune, India',
    remote: false,
    salary: '\u20b93.5L - \u20b95L',
    salary_min_usd: 4200, salary_max_usd: 6000, salary_currency: 'INR',
    skills: ['Java', 'SQL', 'Git', 'Data Structures'],
    description: 'Great opportunity for freshers. Work with global clients on Java/enterprise projects.',
    hiring_speed: 'Slow', company_logo: 'TC', posted: '6 days ago', type: 'Full-time',
    apply_url: 'https://www.tcs.com/careers', source: 'seed', country: 'IN', category: 'Software',
  },
  {
    title: 'Product Manager - Growth',
    company: 'Notion',
    location: 'Remote',
    remote: true,
    salary: '$180K - $240K',
    salary_min_usd: 180000, salary_max_usd: 240000, salary_currency: 'USD',
    skills: ['Product Management', 'SQL', 'A/B Testing', 'User Research', 'Roadmapping', 'Analytics'],
    description: 'Own the growth roadmap at Notion. Partner with engineering, design and marketing to unlock new user acquisition channels.',
    hiring_speed: 'Moderate', company_logo: 'NT', posted: '2 days ago', type: 'Full-time',
    apply_url: 'https://www.notion.so/careers', source: 'seed', country: 'US', category: 'Product',
  },
]
