export const SEED_JOBS = [
  {
    title: 'Senior QA Automation Engineer',
    company: 'Stripe',
    location: 'Remote',
    remote: true,
    salary: '$140K - $180K',
    skills: ['Playwright', 'TypeScript', 'CI/CD', 'API Testing', 'SQL', 'Postman'],
    description: 'Build and maintain end-to-end automation for payment flows using Playwright and TypeScript. Own CI pipelines, write API tests, and partner with engineering to raise the release quality bar.',
    hiring_speed: 'Fast',
    company_logo: 'ST',
    posted: '2 days ago',
    type: 'Full-time',
  },
  {
    title: 'Manual Software Tester',
    company: 'Infosys',
    location: 'Bengaluru, India',
    remote: false,
    salary: '₹4L - ₹8L',
    skills: ['Manual Testing', 'JIRA', 'Test Cases', 'Agile', 'Bug Reporting', 'Regression'],
    description: 'Perform functional and regression testing across web and mobile applications. Author test cases in JIRA, execute test plans, and report defects with clear repro steps.',
    hiring_speed: 'Moderate',
    company_logo: 'IN',
    posted: '1 day ago',
    type: 'Full-time',
  },
  {
    title: 'Full Stack Software Engineer',
    company: 'Vercel',
    location: 'Remote (US)',
    remote: true,
    salary: '$160K - $220K',
    skills: ['Next.js', 'React', 'TypeScript', 'Node.js', 'PostgreSQL', 'AWS'],
    description: 'Build the future of the web at Vercel. Ship product features across our Next.js, edge runtime and dashboard stack. Deep collaboration with design and DX.',
    hiring_speed: 'Fast',
    company_logo: 'VC',
    posted: '5 hours ago',
    type: 'Full-time',
  },
  {
    title: 'SDET - QA Engineer',
    company: 'Zoho',
    location: 'Chennai, India',
    remote: false,
    salary: '₹8L - ₹14L',
    skills: ['Selenium', 'Java', 'TestNG', 'SQL', 'API Testing', 'Postman'],
    description: 'Design, develop and maintain automated test frameworks using Selenium + Java. Write robust API tests and collaborate with dev teams on quality strategy.',
    hiring_speed: 'Fast',
    company_logo: 'ZH',
    posted: '3 days ago',
    type: 'Full-time',
  },
  {
    title: 'Frontend Engineer (React)',
    company: 'Linear',
    location: 'Remote',
    remote: true,
    salary: '$150K - $200K',
    skills: ['React', 'TypeScript', 'CSS', 'Zustand', 'Design Systems', 'Framer Motion'],
    description: 'Craft high-performance interfaces with obsessive attention to detail. You will own major surface areas of the Linear app.',
    hiring_speed: 'Moderate',
    company_logo: 'LI',
    posted: '1 week ago',
    type: 'Full-time',
  },
  {
    title: 'Data Engineer',
    company: 'Razorpay',
    location: 'Bengaluru, India',
    remote: false,
    salary: '₹18L - ₹32L',
    skills: ['Python', 'SQL', 'Airflow', 'Spark', 'AWS', 'Data Modeling'],
    description: 'Build data pipelines that power analytics and ML at Razorpay. Design robust ETL/ELT workflows on Airflow and Spark.',
    hiring_speed: 'Moderate',
    company_logo: 'RZ',
    posted: '4 days ago',
    type: 'Full-time',
  },
  {
    title: 'Junior Software Engineer (Fresher)',
    company: 'TCS',
    location: 'Pune, India',
    remote: false,
    salary: '₹3.5L - ₹5L',
    skills: ['Java', 'SQL', 'OOP', 'Git', 'Data Structures', 'Problem Solving'],
    description: 'Great opportunity for freshers. Work with global clients on Java/enterprise projects. Structured training program included.',
    hiring_speed: 'Slow',
    company_logo: 'TC',
    posted: '6 days ago',
    type: 'Full-time',
  },
  {
    title: 'Product Manager - Growth',
    company: 'Notion',
    location: 'Remote',
    remote: true,
    salary: '$180K - $240K',
    skills: ['Product Strategy', 'SQL', 'A/B Testing', 'User Research', 'Roadmapping', 'Analytics'],
    description: 'Own the growth roadmap at Notion. Partner with engineering, design and marketing to unlock new user acquisition channels.',
    hiring_speed: 'Moderate',
    company_logo: 'NT',
    posted: '2 days ago',
    type: 'Full-time',
  },
]
